### ISSUE TITLE
This example doesn't work

### ISSUE THREAD

**Issue by Panchich** [dotnet/dotnet-api-docs.ru-ru#12]
Something wrong with using, anytime I try to synthesize a speech, I get errors:

Error	CS0234	The type or namespace name 'Speech' does not exist in the namespace 'System' (are you missing an assembly reference?)	ConsoleApp1	
 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 64a3dcf5-80df-e999-4725-8b6c1a894dde
* Version Independent ID: 9b549a9a-9954-eed4-de64-581f629069fa
* Content: [SpeechSynthesizer Class (System.Speech.Synthesis)](https://docs.microsoft.com/ru-ru/dotnet/api/system.speech.synthesis.speechsynthesizer?view=netframework-4.8)
* Content Source: [xml/System.Speech.Synthesis/SpeechSynthesizer.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.Speech.Synthesis/SpeechSynthesizer.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #1885](https://github.com/dotnet/dotnet-api-docs/issues/1885) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Panchich 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/1885

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
