### ISSUE TITLE
Archive bit

### ISSUE THREAD

**Issue by Snegovikufa** [dotnet/dotnet-api-docs.ru-ru#14]
According to https://en.wikipedia.org/wiki/Archive_bit seems that documentation for "Archive" field is wrong.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7001712c-bcbb-d062-d857-cc94398fa32c
* Version Independent ID: bf49dcd7-ad7f-309a-53b0-c616a0f73951
* Content: [FileAttributes Enum (System.IO)](https://docs.microsoft.com/ru-ru/dotnet/api/system.io.fileattributes?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.IO/FileAttributes.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.IO/FileAttributes.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #1992](https://github.com/dotnet/dotnet-api-docs/issues/1992) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Snegovikufa 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/1992

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
