### ISSUE TITLE
Add more clarity

### ISSUE THREAD

**Issue by vasiliuk** [dotnet/dotnet-api-docs.ru-ru#16]
It is not clear if this method take into account sizeof(T).
Actually this method increment your reference by elementOffset * sizeof(T);

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c1853c4d-9453-f5eb-081b-b48a6662bfd5
* Version Independent ID: e5454f16-981c-e7d6-a708-311306413e41
* Content: [Unsafe.Add Method (System.Runtime.CompilerServices)](https://docs.microsoft.com/ru-ru/dotnet/api/system.runtime.compilerservices.unsafe.add?view=dotnet-plat-ext-2.1#feedback)
* Content Source: [xml/System.Runtime.CompilerServices/Unsafe.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.Runtime.CompilerServices/Unsafe.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2061](https://github.com/dotnet/dotnet-api-docs/issues/2061) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @vasiliuk 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2061

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
