### ISSUE TITLE
F# Method signature

### ISSUE THREAD

**Issue by SLAVONchick** [dotnet/dotnet-api-docs.ru-ru#17]
Consider edit method signature in F# view mode `static member TryParse : string *  -> bool` to `static member TryParse: string -> bool * int`. And other signatures so that it return `bool * int`

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 04a9b653-1243-1bad-96f9-975cbfac4216
* Version Independent ID: 0f2d885e-e6e5-ad21-c946-5480b37d2ba1
* Content: [Int32.TryParse Method (System)](https://docs.microsoft.com/ru-ru/dotnet/api/system.int32.tryparse?view=netframework-4.7.2#feedback)
* Content Source: [xml/System/Int32.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System/Int32.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2151](https://github.com/dotnet/dotnet-api-docs/issues/2151) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @SLAVONchick 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2151

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
