### ISSUE TITLE
probably this is mistake

### ISSUE THREAD

**Issue by kovalusion** [dotnet/dotnet-api-docs.ru-ru#9]
...different port numbers in server (8080) and client (443) - would not be worked

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 467b61ab-04cc-2a5d-5be8-2fd37034c7fa
* Version Independent ID: 0bf63c68-cad3-3e9e-a5a9-453d40f1dd6d
* Content: [SslStream Class (System.Net.Security)](https://docs.microsoft.com/ru-ru/dotnet/api/system.net.security.sslstream?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Security/SslStream.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.Net.Security/SslStream.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/dotnet-api-docs #1793](https://github.com/dotnet/dotnet-api-docs/issues/1793) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @kovalusion 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/1793.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
